//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルへの変更は、正しくない動作の原因となる場合があります。
//     コードが再生成されます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace View_and_Data.Account
{


    public partial class RegisterExternalLogin
    {



        /// <summary>
        /// userNameForm コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder userNameForm;

        /// <summary>
        /// userName コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox userName;


    }
}
